### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/duply_backup#1]
- [ ] other pip dependencies
- [ ] bucket creation
- [ ] profile creation
- [ ] things to change in profile/conf
- [ ] start backup
- [ ] different aws tier
- [ ] de-glacier, start, monitor, complete, retrieve
